### ISSUE TITLE
Update deno.lock

### ISSUE THREAD

**Issue by 5ouma** [hasundue/molt-action#10]
Even if it's still an experimental feature, I want to use [the lock file update feature](https://github.com/hasundue/molt?tab=readme-ov-file#lock-files) in Molt.
It must be useful to be able to set via Action input but it's OK to add like `deno cache --lock-write ./**/*.ts` before making PR in the `action.yml`.

**Comment by 5ouma** [comment]
I saw https://github.com/hasundue/molt/issues/178.
It might be better to run just `deno cache`?

**Comment by hasundue** [comment]
Thanks for a feedback! That's definitely a feature to be included.

 >  It might be better to run just deno cache?

But this is true at this moment, unfortunately.

For now let me add `pre-commit` input so that you can run `deno cache` for each update:

```yaml
- uses: hasundue/molt-action@v1-rc
  with:
    pre-commit: 'deno cache --lock-write ./**/*.ts'
```
